### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by minjaekwon9** [andrelandgraf/react-datalist-input#53]
Sorry this is not an issue, but I cannot figure out how to disable the default highlighting. Is there an easy way to disable it or will it require editing the package files? Thank you for the help and the great component. Looks really good!

**Comment by andrelandgraf** [comment]
If you inspect the HTML in your app, you will notice that the matching/highlighted part of each item text is wrapped by `mark` HTML element. You could just style the `mark` tags with CSS. Each item will render the following class: `react-datalist-input__listbox-option`. So you could do something like this:

```css
.react-datalist-input__listbox-option mark {
     background: linear-gradient(-100deg, hsla(48,92%,75%,.3), hsla(48,92%,75%,.7) 95%, hsla(48,92%,75%,.1));
     border-radius: 1em 0;
     padding: .5rem;
}
```

Example CSS taken from [here](https://www.abeautifulsite.net/posts/a-clever-way-to-style-the-mark-element/) (looks dope).

You can also replace what is rendered inside each `li` element by passing in a `node` prop. Find more information about custom item components [in the documentation](https://github.com/andrelandgraf/react-datalist-input#custom-item-components).

I hope this helps!
